INSERT INTO pcg2005(numero,designation)
VALUES ('60120', 'SEMENCES & PLANTS'),
('60111', 'ENGRAIS & ASSIMILES'),
('60260', 'EMBALLAGES'),
('60680', 'ACHATS D AUTRES MATIERES ET FOURNITURES'),
('60610', 'FOURNITURES NON STOCKABLES'),
('60620', 'CARBURANTS LUBRIFIANTS'),
('61320', 'LOCATIONS MOBILIERES ET IMMOBILIERES'),
('61500', 'ENTRETIEN ET REPARATIONS'),
('61600', 'PRIMES D ASSURANCE'),
('60640', 'FOURNITURES ADMINISTRATIVES'),
('62600', 'FRAIS POSTAUX ET DE TELECOMMUNICATIONS'),
('62260', 'HONORAIRES');

INSERT INTO pcg2005(numero,designation)
VALUES ('62410', 'TRANSPORTS SUR ACHAT'),
('62560', 'MISSIONS'),
('62700', 'SERVICES BANCAIRES ET ASSIMILES'),
('62000', 'AUTRES CHARGES EXTERNES'),
('63000', 'IMPOTS ET TAXES'),
('64110', 'SALAIRES ET APPOINTEMENTS'),
('64800', 'AUTRES CHARGES DE PERSONNEL'),
('68000', 'DOTATIONS AUX AMORTISSEMENTS'),
('65000', 'AUTRES CHARGES DE GESTION COURANTE');


create table unite(
    unite VARCHAR(40) primary key
);

insert into unite(unite) values('KG'),('NB'),('Cons periodique'),('KW'),
('LITRES'),('Loyer mensuel'),('Heures de travail (HT)'),('Sal mens ou HT');

create table unite_compte_6(
    libelle VARCHAR(40),
    unite VARCHAR(40),
    foreign key(unite) references unite(unite)
);